Improve EKS token generation and error handling
alisonjenkins/kashay pull request #53
Opened 2023-09-12 14:42 UTC by wmBolles

2023-09-12 17:24 UTC, alisonjenkins requested changes
Need to fix the PR so it doesn't get rid of the role assumption if credentials are not provided and we want to keep the logging on the tests.

Otherwise we can probably get this merged in. I do need to look at some of the code you are removing though which is currently commented as it was commented due to me seeing performance issues around the caching of the credentials.

I need to rework that caching code to make it more performant when I get time to do so.

2023-09-12 17:24 UTC, alisonjenkins commented on src/app/aws.rs
> -    #[test_log::test(tokio::test)]
I actually want test log here as it sets up logging for the tests: https://docs.rs/test-log/latest/test_log/attr.test.html

2023-09-12 17:45 UTC, wmBolles commented
Sorry for the confusion and wasting your time, I'll delete this fork

2023-09-12 17:45 UTC, closed without merging

2023-09-13 08:04 UTC, alisonjenkins commented
> Sorry for the confusion and wasting your time, I'll delete this fork

No problem, thanks for putting in the effort and taking the time to look at the code.

I have just merged some improvements to the codebase inspired from your efforts so they weren't for nothing.

If you wish to help out there is an opportunity for doing some benchmarking here of the sections of code to see if we can make this very fast as the idea of this tool is to get K8s credentials as fast as possible but unfortunatley it has been underperforming but I have as yet not had chance to identify where it is slow and optimise it.

2023-09-14 03:00 UTC, wmBolles commented
<h2>Hi @alisonjenkins</h2> 

<h3>Sorry for the delay in reply.</h3>

Thank you for your feedback and for merging the improvements into the codebase! I appreciate your suggestion for benchmarking, and I agree that optimizing performance is important. I'll prioritize investigating the slow sections to make this tool as fast as possible, in the future.

wassim